config/routes.rb
Rails.application.routes.draw do
  get 'grafica/index'  => 'grafica#index'

  resources :libros
  devise_for :users

  root  to: "libros#index"

end

app/models/libro.rb
class Libro < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/grafica_controller.rb
class GraficaController < ApplicationController
  def index
  	@conteo = Libro.group(:categoria,:formato).count(:formato, :categoria)
  end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.where(user_id: current_user.id)
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:nombre, :precio, :categoria, :formato, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grafica_helper.rb
module GraficaHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/grafica/index.html.erb
<h1>Grafica#index</h1>
<%= link_to "Libros", libros_path %>

   <div style="float:left;">
        <div id="libros_grafica"></div>
    </div> 

<p>Find me in app/views/grafica/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JeysonCorreaMartinez</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>

<%= yield %>


		<p class="navbar-text pull-right">
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
		</p>
</div>

<!--
     Scripts de graficas estadisticas
 -->  

  <script class="include" language="javascript" type="text/javascript" src="/assets/graficas/js/jquery.jqplot.js"></script>

  <script class="include" language="javascript" type="text/javascript" src="/assets/graficas/js/jqplot.pieRenderer.js"></script>
  <script class="include" language="javascript" type="text/javascript" src="/assets/graficas/js/jqplot.donutRenderer.js"></script>
  <script class="include" language="javascript" type="text/javascript" src="/assets/graficas/js/jqplot.barRenderer.js"></script>
  <script class="include" type="text/javascript" src="/assets/graficas/js/jqplot.categoryAxisRenderer.js"></script>
  <script class="include" type="text/javascript" src="/assets/graficas/js/jqplot.enhancedLegendRenderer.js"></script>
  <script class="include" type="text/javascript" src="/assets/graficas/js/jqplot.pointLabels.js"></script>

  <!--button type = "button" onclick="imagenBase64('barras');">Imagen</button -->
    <!--
    Stylos de Graficas estadisticas
    -->

    <link rel="stylesheet" href="/assets/graficas/css/jquery.jqplot.css">
</body>
</html>

app/views/libros/_form.html.erb
<%= form_for @libro, :html => { :class => "form-horizontal libro" } do |f| %>

  <% if @libro.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @libro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
     <%=  f.hidden_field :user_id , :value => current_user.id
    %>
  <div class="form-group">
    <%= f.label :nombre, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nombre, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nombre) %>
  </div>
  <div class="form-group">
    <%= f.label :precio, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :precio, :class => 'form-control' %>
    </div>
    <%=f.error_span(:precio) %>
  </div>
  <div class="form-group">

    <%= f.label :categoria, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
       <%= f.select(:categoria, options_for_select(["Acción", "Novela", "Ficcion", "Comedia"]), {:class => 'form-control', :readonly =>'readonly',:name =>'libro[categoria]'}) %>
    </div>
    <%=f.error_span(:categoria) %>
  </div>
  <div class="form-group">
    <%= f.label :formato, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
           <%= f.select(:formato, options_for_select(["Impreso", "Fisico","Digital"]), {:class => 'form-control', :readonly =>'readonly', :name =>'libro[formato]'}) 
           %>
    </div>
    <%=f.error_span(:formato) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                libros_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/libros/edit.html.erb
<%- model_class = Libro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/libros/grafico_libros.html.erb
   <div style="float:left;">
        <div id="libros_grafica"></div>
    </div> 

app/views/libros/index.html.erb
<div class="row">
 <div class="col align-self-start">
<%- model_class = Libro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to "Ver Grafica",grafica_index_path, :class => "btn btn-success" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:precio) %></th>
      <th><%= model_class.human_attribute_name(:categoria) %></th>
      <th><%= model_class.human_attribute_name(:formato) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

    <% @libros.each do |libro| %>
      <tr>
        <td><%= link_to libro.id, libro_path(libro) %></td>
        <td><%= libro.nombre %></td>
        <td><%= libro.precio %></td>
        <td><%= libro.categoria %></td>
        <td><%= libro.formato %></td>
        <td><%=l libro.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_libro_path(libro), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      libro_path(libro),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_libro_path,
            :class => 'btn btn-primary' %>
 </div>
</div>            

app/views/libros/new.html.erb
<%- model_class = Libro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/libros/show.html.erb
<%- model_class = Libro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @libro.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio) %>:</strong></dt>
  <dd><%= @libro.precio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:categoria) %>:</strong></dt>
  <dd><%= @libro.categoria %></dd>
  <dt><strong><%= model_class.human_attribute_name(:formato) %>:</strong></dt>
  <dd><%= @libro.formato %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              libros_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_libro_path(@libro), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              libro_path(@libro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>